AuthorService and AuthorController creation
cavalcantgus/book-recommendation-system pull request #6
Opened 2024-07-06 01:11 UTC by cavalcantgus

Adicionando um novo serviço e controlador para gerenciar autores. As seguintes alterações foram feitas:

- Criação da classe `AuthorService` para lidar com a lógica de negócios relacionada aos autores.
- Criação da classe `AuthorController` para lidar com solicitações HTTP relacionadas aos autores.
- Adicionados endpoints necessários para criar, atualizar, excluir e buscar autores.

Foram feitos testes manuais simulando requisições das 4 operações de CRUD utilizando a ferramenta Postman

2024-07-06 14:57 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/controllers/AuthorController.java
> +	public ResponseEntity<Author> insert(@RequestBody Author obj) {
```suggestion
	public ResponseEntity<Author> insert(@RequestBody Author author) {
```

2024-07-06 15:02 UTC, cavalcantigor requested changes

2024-07-06 15:02 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/controllers/AuthorController.java
> +			e.getStackTrace();
poderia tratar e lancar a excecao ao requisitante. vai suprimir a exception e nao dar nenhuma informacao ao requisitante que deu erro?

2024-07-06 15:02 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/services/AuthorService.java
> +		return list;
```suggestion
		return repository.findAll();
```

2024-07-06 15:02 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/services/AuthorService.java
> +			e.getMessage();
mesma coisa aqui... ta suprimindo a exception e nao ta dando feedback

2024-07-06 15:02 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/services/AuthorService.java
> +				throw new ResourceNotFoundException(id);
procura sobre log4j e adiciona um log na tua aplicacao. toda excecao precede uma mensagem de log informativa. é uma prática comum e adotada por todo software comercial

2024-07-06 15:02 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/services/AuthorService.java
> +				updateData(author, authorTarget);
isso aqui nao é legal. a gente chama isso de `side effect`. tu muta o objeto dentro do metodo e nao faz nenhum retorno. uma maneira de corrigir seria:
```
Author updatedAuthor = updateData(...)
```

dessa maneira tu nao muta o objeto. tu cria um novo a partir do que foi dado.

2024-07-06 22:55 UTC, cavalcantgus commented
Alterações feitas em AuthorController:

- Mudança do nome da variável `obj` para `author` no método `insert`.
- Tratamento das exceções lançadas no método `patch`.

Alterações feitas em AuthorService:

- Mudança no retorno do método `findAll`.
- Tratamento das exceções no método `update` e `delete` além da adição de logs .
- Redução do side effect no método `update`.

Demais alterações:

- Adicionada a dependência do Log4j2.
- Criado o arquivo de configuração `log4j2-spring.xml`.

2024-07-08 12:05 UTC, cavalcantigor commented on src/main/resources/log4j2-spring.xml
> +        <Logger name="com.baeldung" level="trace"></Logger>
esse nível de log é muito baixo. ele vai logar tudo quanto é coisa. botaria info ou error. olha depois sobre níveis de logs e como são feitos

2024-07-08 12:08 UTC, cavalcantigor commented on src/main/resources/log4j2-spring.xml
> +        <Logger name="com.baeldung" level="trace"></Logger>
tu tem algum pacote `com.baeldung` na tua aplicação? copiou o arquivo e não entendeu ele

2024-07-08 12:10 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/services/AuthorService.java
> +			logger.error("Error while updating author with ID " + id, e);
percebe que na linha 60 lança a exceção que não consegue ser capturada aqui. a exceção lá é `ResourceNotFoundException`. Aqui captura apenas `EntityNotFoundException`.

2024-07-08 12:10 UTC, cavalcantigor commented on src/main/java/com/cavalcantgus/book_recommendation_system/exceptions/DatabaseException.java
> +	private static final long serialVersionUID = 1L;
acho que isso aqui não é necessário

2024-07-12 13:24 UTC, cavalcantigor commented on .gitignore
> +*.log
não pegou o arquivo de log pq a regex não tá cobrindo ele. sugiro adicionar as linhas:

```suggestion
*.log
*.log.*
logs/
```

2024-07-13 18:01 UTC, cavalcantgus commented
### Alterações feitas:

1.  Melhoria no tratamento de exceção do método `update`. 
- Uma exceção `ResourceNotFoundException` é lançada antes da chamada do método `updateData`, garantindo que o id fornecido realmente existe.

- O bloco `catch (ResourceNotFoundException e)` captura uma `ResourceNotFoundException` e relança a exceção original e mantém a mesma stack.

2.  Remoção do número serial na classe `DatabaseException`.

3. Adição das linhas `*.log.*` e `logs/` no .gitignore, conforme sugerido.

4.  Melhoria na configuração do arquivo de log, declarando appenders específicos para logs de nível `ERROR` e ajustando os níveis de log para DEBUG no pacote da aplicação.

2024-07-15 00:11 UTC, cavalcantigor approved these changes

2024-07-15 23:26 UTC, merged